### ISSUE TITLE
Add widget

### ISSUE THREAD

**Issue by mr-Abdrahimov** [wpl-agency/events-tracker-for-elementor#15]
How to add **uael-modal-popup** widget to the list?

I added to the list
private $allowed_widget = array( 'uael-modal-popup', 'button', 'form', 'heading', 'image', 'icon-list', 'call-to-action' );

I just can't figure out what to add to hooks

help me please :)

**Comment by mihdan** [comment]
Ultimate Addons for Elementor this is not a Elementor. This is feature for a PRO version
