### ISSUE TITLE
Error when activated

### ISSUE THREAD

**Issue by ville-e** [wpl-agency/events-tracker-for-elementor#39]
### Discussed in https://github.com/wpl-agency/events-tracker-for-elementor/discussions/38

<div type='discussions-op-text'>

<sup>Originally posted by **ville-e** May 31, 2022</sup>
Hi, please see how it looks when the latest version of the plugin is enabled (1.2.10)

https://i.imgur.com/XFJFiPT.png
</div>

**Comment by ijjimem** [comment]
How to get older version?

**Comment by mihdan** [comment]
Fixed in 1.3.0
