### ISSUE TITLE
Status of plugin? Wordpress plugin page indicates this plugin has been removed pending review

### ISSUE THREAD

**Issue by localpcguy** [wpl-agency/events-tracker-for-elementor#50]
Writing to ask about the status of this plugin. It has been useful, but if it is no longer supported, it would be nice to know.

See: https://wordpress.org/plugins/events-tracker-for-elementor/

> This plugin has been closed as of July 10, 2024 and is not available for download. This closure is temporary, pending a full review.

![image](https://github.com/user-attachments/assets/d3bc4f29-b4d9-4b5c-934c-0a044b7cbb51)

**Comment by mihdan** [comment]
Oops, we'll try to restore the plugin

**Comment by localpcguy** [comment]
On the Wordpress site, it now says it's closed due to Guideline Violation:

![image](https://github.com/user-attachments/assets/08bcdb82-1402-4f0f-95f9-17c66926e636)

**Comment by mihdan** [comment]
Hello colleagues.

We are working on restoring the plugin to the wp.org repository.

**Comment by mihdan** [comment]
Hello colleagues.

We have restored the plugin to the wp.org repository
